/*
 * dgMaster: A versatile, open source data generator.
 *(c) 2007 M. Michalakopoulos, mmichalak@gmail.com
 */




package generator.gui;

import javax.swing.text.html.HTMLEditorKit;
/*
 * AboutPanel.java
 *
 * Created on 11 May 2007, 04:34
 */

public class AboutPanel extends javax.swing.JPanel
{
    String msg;
    /** Creates new form AboutPanel */
    public AboutPanel()
    {
        initComponents();
        txtInfo.setEditorKit( new HTMLEditorKit() );
        setInfo();
    }
    
    private void setInfo()
    {
        msg="<html><body>"+
            "<b>dgMaster v2.0</b>: a versatile, open source data generator." +
            "<br>(c)2007-2009 Michael Michalakopoulos mmichalak@gmail.com, " +
            "<a href='http://www.mmichalak.info'>www.mmichalak.info<a>, " +
            " <a href='http://www.dgmaster.org'>www.dgmaster.org</a> <br><br>" +
            ". The software is released under the GPL Licence. In short, this means" +
            " that you are allowed to freely distribute and/or modify the program," +
            " provided that your derived work is also released under the GPL licence," +
            " (that is, your derived work stays within the open source community)." +
            "<br><br>" +
            "Copyright notices in the source files, should be kept there; If you are" +
            " re-distributing dgMaster, make sure you include the file \"readme_licence.txt\" "+
            "in the files you release. The file \"apache_licence.txt\" contains the apache" +
            " licence, since dgMaster uses log4j.<br><br>" +
            "<b>Credits</b><br>" +
            "Third party libraries:<br>" +
            "Log4j<br><br>" +
            "Databene benerator (used in regular expressions generator)<br>" +
            "<a href='http://databene.org/databene-benerator'>databene.org/databene-benerator</a><br><br>" +
            "Icons:<br>" +
            "Largely from the Tango project<br>" +
            "<a href='http://tango.freedesktop.org/Tango_Desktop_Project'>tango.freedesktop.org/Tango_Desktop_Project</a>" +
            "<br><br>" +
            "Some icons from the silk collection<br>" +
            "<a href='http://www.famfamfam.com/lab/icons/silk/'>www.famfamfam.com/lab/icons/silk</a>"+
            "</body></html>";
        txtInfo.setText(msg);
        txtInfo.setSelectionStart(1);
        txtInfo.moveCaretPosition(1);
        txtInfo.setSelectionEnd(1);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JEditorPane();

        btnClose.setText("Close");
        btnClose.setAutoscrolls(true);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane txtInfo;
    // End of variables declaration//GEN-END:variables
    
}
