/*
 * DBScenarioLoadPanel.java
 *
 * Created on 18 October 2008, 16:05
 */

package generator.gui;

import generator.db.DBGeneratorDefinition;
import generator.engine.ProgressUpdateObserver;
import generator.engine.db.Generator;
import generator.misc.DBFileDefinition;
import generator.misc.DBGenDefSAXHandler;
import generator.misc.RandomDefinitionsBuilder;
import java.util.Vector;
import javax.swing.JProgressBar;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

/**
 *
 * @author  Michael
 */
public class DBScenarioLoadPanel extends javax.swing.JPanel implements ProgressUpdateObserver
{
    
    public boolean cancel = false;
    
    /** Creates new form DBScenarioLoadPanel */
    public DBScenarioLoadPanel()
    {
        initComponents();
    }
    
    public void setDBScenario(DBFileDefinition dbd)
    {
//        txtScenario.setText( dbd.getScenario() );
//        txtDescription.setText( dbd.getDescription() );
//        txtFilename.setText( dbd.getLinkFileDB() );
//        
//        RandomDefinitionsBuilder builder = new RandomDefinitionsBuilder();
//        builder.setFilename( txtFilename.getText() );
//        builder.setSAXHandler( new DBGenDefSAXHandler() );
//        Vector vData = builder.getElements();
//        
//        DBGeneratorDefinition dbGenDefinition = (DBGeneratorDefinition) vData.get(0);
//        
//        spinCycles.setValue( dbGenDefinition.getCycles() );
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDBScenario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtScenario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        spinCycles = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txtFilename = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnExecute = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessages = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();

        pnlDBScenario.setBorder(javax.swing.BorderFactory.createTitledBorder("Database Scenario"));

        jLabel1.setText("Name: ");

        jLabel2.setText("Filename:");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescription);

        jLabel3.setText("Num of recs:");

        jLabel4.setText("Description:");

        javax.swing.GroupLayout pnlDBScenarioLayout = new javax.swing.GroupLayout(pnlDBScenario);
        pnlDBScenario.setLayout(pnlDBScenarioLayout);
        pnlDBScenarioLayout.setHorizontalGroup(
            pnlDBScenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDBScenarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDBScenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDBScenarioLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnlDBScenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDBScenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addComponent(txtFilename, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addGroup(pnlDBScenarioLayout.createSequentialGroup()
                        .addComponent(spinCycles, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlDBScenarioLayout.createSequentialGroup()
                        .addComponent(txtScenario, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(509, Short.MAX_VALUE))))
        );
        pnlDBScenarioLayout.setVerticalGroup(
            pnlDBScenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDBScenarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDBScenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtScenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDBScenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDBScenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDBScenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinCycles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEdit.setText("Edit scenario");

        btnExecute.setText("Load data");
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Messages"));

        txtMessages.setColumns(20);
        txtMessages.setRows(5);
        jScrollPane2.setViewportView(txtMessages);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
        );

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDBScenario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDBScenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnExecute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        cancel = true;
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExecuteActionPerformed
    {//GEN-HEADEREND:event_btnExecuteActionPerformed
        final Generator generator;
        final DBGeneratorDefinition dbGenDefinition;
        final ProgressUpdateObserver observer = this;
        
        cancel = false;
        RandomDefinitionsBuilder builder = new RandomDefinitionsBuilder();
        builder.setFilename( txtFilename.getText() );
        builder.setSAXHandler( new DBGenDefSAXHandler() );
        Vector vData = builder.getElements();
        
        dbGenDefinition = (DBGeneratorDefinition) vData.get(0);
        generator = new Generator();                       
        
        SwingWorker worker = new SwingWorker()
        {
            public Object construct()
            {
                generator.setDBGeneratorDefinition(dbGenDefinition);
                generator.registerObserver(observer);
                generator.generate();
                return null;
            }
        };
        worker.start();
    }//GEN-LAST:event_btnExecuteActionPerformed
    
    public void dataGenStarted()
    {
        txtMessages.append("Starting data generation\n");
    }
    
    public void dataGenMaxProgressValue(int maxProgress)
    {
        txtMessages.append("Max progress: " +maxProgress +"\n");
        progressBar.setMaximum(maxProgress);
    }
    
    public boolean dataGenProgressContinue(String msg, int progress)
    {
        final int v=progress;
        final String s = msg;
        final JProgressBar progBar = progressBar;
        final JTextArea area = txtMessages;
        final String m = msg;
        
        SwingUtilities.invokeLater( new Runnable()
        {
            public void run()
            {
                 progBar.setValue(v);
                 //frmProgress.setLabelMessage(s);
                 area.append(m + ", " + v + "\n");
            }
        });                        
        
        return cancel;
    }
    
    public void dataGenEnd()
    {
        txtMessages.append("Ending data generation\n");
    }
    
    public void datageGenError(String msg)
    {
        txtMessages.append(msg+"\n");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExecute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlDBScenario;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JSpinner spinCycles;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtFilename;
    private javax.swing.JTextArea txtMessages;
    private javax.swing.JTextField txtScenario;
    // End of variables declaration//GEN-END:variables
    
}
