/*
 * NotImplementedPanel.java
 *
 * Created on 26 May 2007, 14:46
 */

package generator.gui;

import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author  Michael
 */
public class NotImplementedPanel extends javax.swing.JPanel
{
    String msg;
    /** Creates new form NotImplementedPanel */
    public NotImplementedPanel()
    {
        initComponents();
        msg = "<html><body>This feature has not been implemented yet.<br><br>" +
              "I know it is dissappointing, but I am working on it...<br><br>" +
              "Generating database data is not feasible yet, despite the fact " + 
              "you may be able to retrieve database metadata<br><br><br>" +
              "See <a href=\"dgmaster.sourceforge.net\">dgmaster.sourceforge.net</a> " +
                " for project updates and related information.<br><br>" +
              "<b>---Thank you for downloading this software, stay tuned!</b></body></html>";
        txtInfo.setEditorKit( new HTMLEditorKit() );
        txtInfo.setText(msg);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDismiss = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JEditorPane();

        btnDismiss.setText("OK");
        btnDismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDismissActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtInfo);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(btnDismiss, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnDismiss)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDismissActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDismissActionPerformed
    {//GEN-HEADEREND:event_btnDismissActionPerformed
        getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_btnDismissActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDismiss;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane txtInfo;
    // End of variables declaration//GEN-END:variables
    
}
