package com.gruter.generator.randomisers;

import java.util.LinkedHashMap;

import javax.swing.JOptionPane;

import generator.extenders.RandomiserInstance;
import generator.extenders.RandomiserPanel;

import org.apache.log4j.Logger;

@SuppressWarnings("serial")
public class PanelIPRandomiser extends RandomiserPanel {
  Logger logger = Logger.getLogger(PanelIPRandomiser.class);

  public PanelIPRandomiser() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {
    jPanel2 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    txtName = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtDescription = new javax.swing.JTextArea();

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Case description"));
    jPanel2.setName("jPanel2"); // NOI18N

    jLabel4.setText("Name:");
    jLabel4.setName("jLabel4"); // NOI18N

    jLabel5.setText("Description:");
    jLabel5.setName("jLabel5"); // NOI18N

    txtName.setName("txtName"); // NOI18N

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    txtDescription.setColumns(20);
    txtDescription.setFont(new java.awt.Font("Tahoma", 0, 11));
    txtDescription.setLineWrap(true);
    txtDescription.setRows(5);
    txtDescription.setName("txtDescription"); // NOI18N
    jScrollPane1.setViewportView(txtDescription);

    org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(txtName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel4)
                .add(txtName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jLabel5)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
            .addContainerGap())
    );

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
            .add(10, 10, 10)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(101, Short.MAX_VALUE))
    );    
  }// </editor-fold>

  public boolean isFormValid() {
    if (txtName.getText().trim().length() == 0) {
      JOptionPane.showMessageDialog(this, "Please provide a value for the name", "Required field",
          JOptionPane.ERROR_MESSAGE);
      return false;
    }
    
    return true;
  }

  public RandomiserInstance getRandomiserInstance() {
    RandomiserInstance ri = new RandomiserInstance();
    LinkedHashMap<String, String> hashmap = new LinkedHashMap<String, String>();
    
    ri.setName(txtName.getText());
    ri.setDescription(txtDescription.getText());
    ri.setRandomiserType("IPRandomiser");
    ri.setProperties(hashmap);
    
    return ri;
  }

  public void initialise(RandomiserInstance ri) {
    txtName.setText(ri.getName());
    txtDescription.setText(ri.getDescription());
  }

  // Variables declaration - do not modify
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea txtDescription;
  private javax.swing.JTextField txtName;  
  // End of variables declaration

}
